config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'change_password/:id', to: 'password#edit', as: 'edit_password'
  patch 'change_password/:id', to: 'password#update', as: 'update_password'

  get 'signup', to: 'users#new'

  resources :articles do
    resources :comments, only: [:create, :destroy]
  end
  resources :articles
  resources :themes
  resources :article_approvals, only: [:index, :show, :update]
  resources :users, only: [:index, :show, :edit, :update, :new, :create] do
    member do
      get :articles
      get :comments
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  after_create :create_approval_request

  belongs_to :user
  belongs_to :theme
  has_many :comments, dependent: :destroy
  has_one :article_approval, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :theme_id, presence: true

  private

  def create_approval_request
    ArticleApproval.create(article: self, status: 'pending')
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]

  def index
    @articles = @articles
    @articles = Article.all
    @articles = @articles.where(theme_id: params[:theme_id]) if params[:theme_id].present?
  end

  def show
    @comment = Comment.new
  end

  def new
    @article = Article.new
    @themes = Theme.all
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      ArticleApproval.create(article: @article, status: 'pending')
      redirect_to @article, notice: 'Article submitted for approval.'
    else
      flash.now[:alert] = 'There was an error creating the article.'
      @themes = Theme.all
      render :new
    end
  end

  def edit
    @themes = Theme.all
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      @themes = Theme.all
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully deleted.'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :theme_id)
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>

  <p>
    <strong>User:</strong>
    <%= article.user_id %>
  </p>

  <p>
    <strong>Theme:</strong>
    <%= article.theme_id %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>


  <div>
        <%= form.collection_select :theme_id, Theme.all, :id, :name, { prompt: "Select a theme" }%>
      
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<% content_for :title, "Editing article" %>

<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<!-- app/views/articles/index.html.erb -->
<h1>Articles</h1>

<%= form_tag articles_path, method: :get, class: 'mb-4' do %>
  <%= select_tag :theme_id, options_from_collection_for_select(Theme.all, :id, :name, params[:theme_id]), prompt: "Filter by Theme", class: 'form-select' %>
  <%= submit_tag "Filter", class: 'btn btn-primary mt-2' %>
<% end %>

<div class="row">
  <% @articles.each do |article| %>
    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
          <p class="card-text"><%= truncate(article.body, length: 100) %></p>
          <p class="card-text"><small class="text-muted">Theme: <%= article.theme.name %></small></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Article', new_article_path, class: 'btn btn-primary' if true %> 

app/views/articles/new.html.erb
<% content_for :title, "New article" %>

<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<!-- app/views/articles/show.html.erb -->
<h1><%= @article.title %></h1>
<p><strong>Theme:</strong> <%= @article.theme.name %></p>
<p><strong>Author:</strong> <%= @article.user.username %></p>

<div class="article-body">
  <%= simple_format(@article.body) %>
</div>

<% if logged_in? && current_user == @article.user %>
  <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-secondary' %>
  <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<% end %>


<% if true %>
  <h3>Add a comment:</h3>
  <%= render 'comments/form' %>
<% else %>
  <p>Please <%= link_to 'log in', new_user_session_path %> to add a comment.</p>
<% end %>

<h2 class="mt-4">Comments</h2>
<%= render @article.comments %>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>