config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'change_password/:id', to: 'password#edit', as: 'edit_password'
  patch 'change_password/:id', to: 'password#update', as: 'update_password'

  get 'signup', to: 'users#new'

  resources :articles do
    resources :comments, only: [:create, :destroy]
  end
  resources :articles
  resources :themes
  resources :article_approvals, only: [:index, :show, :update]
  resources :users, only: [:index, :show, :edit, :update, :new, :create] do
    member do
      get :articles
      get :comments
    end
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
    has_many :articles, dependent: :nullify
  
    validates :name, presence: true, uniqueness: true
  end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  def index
    @themes = Theme.all
    @themes = @themes
  end

  def show
    @articles = @theme.articles
  end

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(theme_params)
    if @theme.save
      redirect_to @theme, notice: 'Theme created successfully.'
    else
      render :new
    end
  end

  private

  def set_theme
    @theme = Theme.find(params[:id])
  end

  def theme_params
    params.require(:theme).permit(:name)
  end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<%= form_with(model: theme) do |form| %>
  <% if theme.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
        <% theme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :theme_name, style: "display: block" %>
    <%= form.text_field :theme_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/themes/_theme.html.erb
<div id="<%= dom_id theme %>">
  <p>
    <strong>Theme name:</strong>
    <%= theme.theme_name %>
  </p>

</div>

app/views/themes/create.html.erb
<h1>Themes#create</h1>
<p>Find me in app/views/themes/create.html.erb</p>

app/views/themes/destroy.html.erb
<h1>Themes#destroy</h1>
<p>Find me in app/views/themes/destroy.html.erb</p>

app/views/themes/edit.html.erb
<% content_for :title, "Editing theme" %>

<h1>Editing theme</h1>

<%= render "form", theme: @theme %>

<br>

<div>
  <%= link_to "Show this theme", @theme %> |
  <%= link_to "Back to themes", themes_path %>
</div>

app/views/themes/index.html.erb
<!-- app/views/themes/index.html.erb -->
<h1>Themes</h1>

<div class="row">
  <% @themes.each do |theme| %>
    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= link_to theme.name, theme_path(theme) %></h5>
          <p class="card-text"><%= pluralize(theme.articles.count, 'article') %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Theme', new_theme_path, class: 'btn btn-primary' if logged_in? %>

app/views/themes/new.html.erb
<% content_for :title, "New theme" %>

<h1>New theme</h1>

<%= render "form", theme: @theme %>

<br>

<div>
  <%= link_to "Back to themes", themes_path %>
</div>

app/views/themes/show.html.erb
<!-- app/views/themes/show.html.erb -->
<h1><%= @theme.name %></h1>

<h2>Articles in this theme:</h2>
<div class="row">
  <% @articles.each do |article| %>
    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
          <p class="card-text"><%= truncate(article.body, length: 100) %></p>
          <p class="card-text"><small class="text-muted">By <%= article.user.username %></small></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'Back to Themes', themes_path, class: 'btn btn-secondary' %>

app/views/themes/update.html.erb
<h1>Themes#update</h1>
<p>Find me in app/views/themes/update.html.erb</p>