config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'change_password/:id', to: 'password#edit', as: 'edit_password'
  patch 'change_password/:id', to: 'password#update', as: 'update_password'

  get 'signup', to: 'users#new'

  resources :articles do
    resources :comments, only: [:create, :destroy]
  end
  resources :articles
  resources :themes
  resources :article_approvals, only: [:index, :show, :update]
  resources :users, only: [:index, :show, :edit, :update, :new, :create] do
    member do
      get :articles
      get :comments
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum user_role: {user: 'user', moderator: 'moderator', admin: 'admin'}

  has_many :articles
  has_many :comments
  has_many :article_approvals, foreign_key: 'approved_by_id'

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :user_role, presence: true
  validates :password, length: { minimum: 12 }, if: -> { new_record? || !password.nil? }

  has_secure_password

  # Add any authentication logic here (e.g., has_secure_password if using bcrypt)
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:index, :show, :new, :create]
  before_action :authorize_user, only: [:show ]

  def index
    @users = User.all 
    @users = @users
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'User created successfully.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User updated successfully.'
    else
      render :edit, notice: 'There was an error updating the user.'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User deleted successfully.'
  end

  private

  def set_user
    @user = User.find(params[:id])
    unless @user
      redirect_to users_path, alert: 'User not found.'
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :user_role)
  end  



  def authorize_user
    unless current_user.admin? || current_user == @user
      flash[:alert] = "You are not authorized to view this profile."
      redirect_to root_path
    end
  end

  def admin?
    current_user.user_role == "admin"
  end
  def moderator?
    current_user.user_role == "moderator"
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :user_role_id, style: "display: block" %>
    <%= form.text_field :user_role_id %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.text_field :password_digest %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>User role:</strong>
    <%= user.user_role_id %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= form_with(model: @user, local: true) do |form| %>
  <%= form.label :username %>
  <%= form.text_field :username %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :user_role%>
    <%= form.select :user_role, ['admin', 'moderator', 'user'], { include_blank: "Select a role" }, class: 'form-control' %>
  <%= form.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Role</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.user_role %></td>
        <td>
          <%= link_to 'View', user_path(user) %>
          <%= link_to 'Edit', edit_user_path(user) if can? :update, user %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with model: @user, local: true do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
  <div>
    <%= form.submit "Sign Up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<p>Email: <%= @user.email %></p>
<p>Created: <%= @user.created_at.strftime('%B %d, %Y') %></p>
<p>Username: <%= @user.username %></p>
<p>Role: <%= @user.user_role %></p>
<div>
  <%= link_to 'Edit', edit_user_path(@user) %>
  <%= link_to 'Change Password', edit_password_path(@user) %>
</div>
<h2>Articles</h2>
<ul>
  <% @user.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>