config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'change_password/:id', to: 'password#edit', as: 'edit_password'
  patch 'change_password/:id', to: 'password#update', as: 'update_password'

  get 'signup', to: 'users#new'

  resources :articles do
    resources :comments, only: [:create, :destroy]
  end
  resources :articles
  resources :themes
  resources :article_approvals, only: [:index, :show, :update]
  resources :users, only: [:index, :show, :edit, :update, :new, :create] do
    member do
      get :articles
      get :comments
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.user_role == "admin"
      can :manage, :all
    elsif user.user_role == "moderator"
      can :manage, Article
      can :manage, Comment
    else
      can :read, :all
      can :create, Article
      can :create, Comment
      can :update, Article, user_id: user.id
      can :destroy, Article, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  has_paper_trail
end

app/models/article.rb
class Article < ApplicationRecord
  after_create :create_approval_request

  belongs_to :user
  belongs_to :theme
  has_many :comments, dependent: :destroy
  has_one :article_approval, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :theme_id, presence: true

  private

  def create_approval_request
    ArticleApproval.create(article: self, status: 'pending')
  end

end

app/models/article_approval.rb
class ArticleApproval < ApplicationRecord
  belongs_to :article
  belongs_to :approved_by, class_name: 'User'

  validates :status, presence: true, inclusion: { in: ['pending', 'approved', 'rejected'] }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :comment_content, presence: true
  validates :user_id, presence: true
end

app/models/theme.rb
class Theme < ApplicationRecord
    has_many :articles, dependent: :nullify
  
    validates :name, presence: true, uniqueness: true
  end

app/models/user.rb
class User < ApplicationRecord
  enum user_role: {user: 'user', moderator: 'moderator', admin: 'admin'}

  has_many :articles
  has_many :comments
  has_many :article_approvals, foreign_key: 'approved_by_id'

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :user_role, presence: true
  validates :password, length: { minimum: 12 }, if: -> { new_record? || !password.nil? }

  has_secure_password

  # Add any authentication logic here (e.g., has_secure_password if using bcrypt)
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]

  def index
    @articles = @articles
    @articles = Article.all
    @articles = @articles.where(theme_id: params[:theme_id]) if params[:theme_id].present?
  end

  def show
    @comment = Comment.new
  end

  def new
    @article = Article.new
    @themes = Theme.all
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      ArticleApproval.create(article: @article, status: 'pending')
      redirect_to @article, notice: 'Article submitted for approval.'
    else
      flash.now[:alert] = 'There was an error creating the article.'
      @themes = Theme.all
      render :new
    end
  end

  def edit
    @themes = Theme.all
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      @themes = Theme.all
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully deleted.'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :theme_id)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  before_action :require_user

  def index
    @comments = @comments
  end

  def create
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @article, notice: 'Comment added successfully.'
    else
      redirect_to @article, alert: 'Failed to add comment. error: ' + @comment.errors.full_messages.join(', ')
    end
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def comment_params
    params.require(:comment).permit(:comment_content)
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :set_user
  
  def edit
  end

  def update
    if @user.authenticate(params[:user][:current_password])
      if @user.update(password_params)
        redirect_to @user, notice: 'Password updated successfully.'
      else
        render :edit, alert: 'There was an error updating the password.'
      end
    else
      flash.now[:alert] = 'Current password is incorrect.'
      render :edit
    end
  end


  private
  def set_user
    @user = User.find(params[:id])
  end
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end 

end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  def index
    @themes = Theme.all
    @themes = @themes
  end

  def show
    @articles = @theme.articles
  end

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(theme_params)
    if @theme.save
      redirect_to @theme, notice: 'Theme created successfully.'
    else
      render :new
    end
  end

  private

  def set_theme
    @theme = Theme.find(params[:id])
  end

  def theme_params
    params.require(:theme).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:index, :show, :new, :create]
  before_action :authorize_user, only: [:show ]

  def index
    @users = User.all 
    @users = @users
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'User created successfully.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User updated successfully.'
    else
      render :edit, notice: 'There was an error updating the user.'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User deleted successfully.'
  end

  private

  def set_user
    @user = User.find(params[:id])
    unless @user
      redirect_to users_path, alert: 'User not found.'
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :user_role)
  end  



  def authorize_user
    unless current_user.admin? || current_user == @user
      flash[:alert] = "You are not authorized to view this profile."
      redirect_to root_path
    end
  end

  def admin?
    current_user.user_role == "admin"
  end
  def moderator?
    current_user.user_role == "moderator"
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardenHive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
      body { background-color: #f0f8ff; } /* Light blue background */
      .navbar { background-color: #4a7c59; } /* Dark green navbar */
      .navbar-brand, .nav-link { color: #ffffff !important; } /* White text for navbar */
      .btn-primary { background-color: #4a7c59; border-color: #4a7c59; } /* Green buttons */
      .btn-primary:hover { background-color: #3a6249; border-color: #3a6249; }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="container">
        <%= link_to 'GardenHive', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Articles', articles_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Themes', themes_path, class: 'nav-link' %>
            </li>
          </ul>
          <ul class="navbar-nav">
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to 'New Article', new_article_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Profile', user_path(current_user), class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Log Out', logout_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Users', users_path, class: 'nav-link' if current_user.admin? %>
              </li>

            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign Up', signup_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Log In', login_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mt-4">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
          <%= value %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>